// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MODEL.Entities.Branch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CreatedComputerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "92998 Margarette Hollow, Bruenshire, Taiwan",
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 232, DateTimeKind.Local).AddTicks(701),
                            Name = "Lindgren, Welch and Funk",
                            PhoneNumber = "3377609905",
                            Status = 0
                        },
                        new
                        {
                            ID = 2,
                            Address = "8995 Wisoky Ranch, Lakinville, Colombia",
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 232, DateTimeKind.Local).AddTicks(1738),
                            Name = "Goyette, Batz and Schmitt",
                            PhoneNumber = "0688446740",
                            Status = 0
                        },
                        new
                        {
                            ID = 3,
                            Address = "552 Renner Plaza, Parisianton, Nigeria",
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 232, DateTimeKind.Local).AddTicks(2057),
                            Name = "Balistreri - Rodriguez",
                            PhoneNumber = "3954950129",
                            Status = 0
                        },
                        new
                        {
                            ID = 4,
                            Address = "6129 Ratke Skyway, Camylleville, New Zealand",
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 232, DateTimeKind.Local).AddTicks(2233),
                            Name = "Smith Inc",
                            PhoneNumber = "4488277562",
                            Status = 0
                        },
                        new
                        {
                            ID = 5,
                            Address = "26185 Mitchell Junction, Alexieberg, Saint Helena",
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 232, DateTimeKind.Local).AddTicks(6822),
                            Name = "Effertz Inc",
                            PhoneNumber = "1829243946",
                            Status = 0
                        });
                });

            modelBuilder.Entity("MODEL.Entities.Schedule", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedComputerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LessonDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "TeacherId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("MODEL.Entities.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CourseHours")
                        .HasColumnType("int");

                    b.Property<string>("CreatedComputerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tckn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength();

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("BranchId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BirthDate = new DateTime(1990, 1, 25, 5, 24, 3, 379, DateTimeKind.Local).AddTicks(3092),
                            BranchId = 1,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(6252),
                            Name = "Andres",
                            Status = 0,
                            Surname = "Kertzmann",
                            Tckn = "14958016265"
                        },
                        new
                        {
                            ID = 2,
                            BirthDate = new DateTime(2005, 7, 5, 12, 25, 20, 784, DateTimeKind.Local).AddTicks(7814),
                            BranchId = 5,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8191),
                            Name = "Brielle",
                            Status = 0,
                            Surname = "Labadie",
                            Tckn = "49018703379"
                        },
                        new
                        {
                            ID = 3,
                            BirthDate = new DateTime(1999, 11, 15, 13, 30, 33, 366, DateTimeKind.Local).AddTicks(24),
                            BranchId = 2,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8257),
                            Name = "Lucienne",
                            Status = 0,
                            Surname = "Erdman",
                            Tckn = "78327486296"
                        },
                        new
                        {
                            ID = 4,
                            BirthDate = new DateTime(2005, 1, 7, 21, 34, 9, 27, DateTimeKind.Local).AddTicks(202),
                            BranchId = 4,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8328),
                            Name = "Bart",
                            Status = 0,
                            Surname = "Emard",
                            Tckn = "98373204263"
                        },
                        new
                        {
                            ID = 5,
                            BirthDate = new DateTime(2003, 4, 15, 21, 46, 44, 368, DateTimeKind.Local).AddTicks(8137),
                            BranchId = 3,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8347),
                            Name = "Robin",
                            Status = 0,
                            Surname = "Romaguera",
                            Tckn = "05043513866"
                        },
                        new
                        {
                            ID = 6,
                            BirthDate = new DateTime(2002, 5, 27, 18, 59, 37, 497, DateTimeKind.Local).AddTicks(1854),
                            BranchId = 2,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8367),
                            Name = "Hailee",
                            Status = 0,
                            Surname = "Doyle",
                            Tckn = "37486985409"
                        },
                        new
                        {
                            ID = 7,
                            BirthDate = new DateTime(1987, 6, 2, 17, 53, 3, 421, DateTimeKind.Local).AddTicks(8117),
                            BranchId = 1,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8390),
                            Name = "Tyrell",
                            Status = 0,
                            Surname = "Gusikowski",
                            Tckn = "61622583823"
                        },
                        new
                        {
                            ID = 8,
                            BirthDate = new DateTime(1997, 7, 2, 10, 33, 6, 409, DateTimeKind.Local).AddTicks(794),
                            BranchId = 2,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8411),
                            Name = "Alexa",
                            Status = 0,
                            Surname = "Considine",
                            Tckn = "80951143787"
                        },
                        new
                        {
                            ID = 9,
                            BirthDate = new DateTime(2003, 1, 13, 19, 46, 21, 631, DateTimeKind.Local).AddTicks(8227),
                            BranchId = 5,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8430),
                            Name = "Kevon",
                            Status = 0,
                            Surname = "Gutmann",
                            Tckn = "02273223110"
                        },
                        new
                        {
                            ID = 10,
                            BirthDate = new DateTime(1991, 7, 14, 22, 27, 44, 925, DateTimeKind.Local).AddTicks(3129),
                            BranchId = 1,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8447),
                            Name = "Jarrod",
                            Status = 0,
                            Surname = "Rowe",
                            Tckn = "14596633767"
                        },
                        new
                        {
                            ID = 11,
                            BirthDate = new DateTime(2005, 3, 31, 8, 23, 31, 975, DateTimeKind.Local).AddTicks(8449),
                            BranchId = 2,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8468),
                            Name = "Jadyn",
                            Status = 0,
                            Surname = "Kessler",
                            Tckn = "51781916388"
                        },
                        new
                        {
                            ID = 12,
                            BirthDate = new DateTime(1995, 10, 23, 19, 31, 52, 823, DateTimeKind.Local).AddTicks(244),
                            BranchId = 3,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8485),
                            Name = "Stewart",
                            Status = 0,
                            Surname = "Weissnat",
                            Tckn = "36988494576"
                        },
                        new
                        {
                            ID = 13,
                            BirthDate = new DateTime(1997, 12, 6, 10, 1, 20, 917, DateTimeKind.Local).AddTicks(6747),
                            BranchId = 1,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8503),
                            Name = "Ernestina",
                            Status = 0,
                            Surname = "Stracke",
                            Tckn = "86314191474"
                        },
                        new
                        {
                            ID = 14,
                            BirthDate = new DateTime(2001, 6, 19, 6, 20, 55, 26, DateTimeKind.Local).AddTicks(7856),
                            BranchId = 5,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8522),
                            Name = "Meggie",
                            Status = 0,
                            Surname = "Bartell",
                            Tckn = "15988620503"
                        },
                        new
                        {
                            ID = 15,
                            BirthDate = new DateTime(1996, 3, 11, 8, 14, 4, 550, DateTimeKind.Local).AddTicks(8526),
                            BranchId = 3,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8544),
                            Name = "Tiffany",
                            Status = 0,
                            Surname = "Marquardt",
                            Tckn = "47213406818"
                        },
                        new
                        {
                            ID = 16,
                            BirthDate = new DateTime(1996, 11, 8, 18, 55, 48, 846, DateTimeKind.Local).AddTicks(4634),
                            BranchId = 2,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8562),
                            Name = "Ernesto",
                            Status = 0,
                            Surname = "Smitham",
                            Tckn = "18832562430"
                        },
                        new
                        {
                            ID = 17,
                            BirthDate = new DateTime(1998, 11, 19, 18, 16, 4, 403, DateTimeKind.Local).AddTicks(4546),
                            BranchId = 1,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8578),
                            Name = "Arlene",
                            Status = 0,
                            Surname = "Lind",
                            Tckn = "10339924593"
                        },
                        new
                        {
                            ID = 18,
                            BirthDate = new DateTime(2006, 5, 12, 7, 14, 49, 333, DateTimeKind.Local).AddTicks(7465),
                            BranchId = 5,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8596),
                            Name = "Timmy",
                            Status = 0,
                            Surname = "Murazik",
                            Tckn = "43371533126"
                        },
                        new
                        {
                            ID = 19,
                            BirthDate = new DateTime(1992, 9, 8, 3, 1, 54, 742, DateTimeKind.Local).AddTicks(1495),
                            BranchId = 2,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8616),
                            Name = "Flo",
                            Status = 0,
                            Surname = "Auer",
                            Tckn = "33423558776"
                        },
                        new
                        {
                            ID = 20,
                            BirthDate = new DateTime(1991, 3, 16, 1, 48, 27, 241, DateTimeKind.Local).AddTicks(1984),
                            BranchId = 5,
                            CourseHours = 6,
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 236, DateTimeKind.Local).AddTicks(8633),
                            Name = "Kobe",
                            Status = 0,
                            Surname = "Lehner",
                            Tckn = "02250785013"
                        });
                });

            modelBuilder.Entity("MODEL.Entities.Teacher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedComputerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tckn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength();

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BirthDate = new DateTime(1993, 11, 11, 6, 1, 47, 784, DateTimeKind.Local).AddTicks(335),
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 235, DateTimeKind.Local).AddTicks(501),
                            Name = "Jamil",
                            Status = 0,
                            Surname = "Veum",
                            Tckn = "35251139674"
                        },
                        new
                        {
                            ID = 2,
                            BirthDate = new DateTime(1999, 3, 26, 4, 4, 39, 318, DateTimeKind.Local).AddTicks(3951),
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 235, DateTimeKind.Local).AddTicks(2073),
                            Name = "Shad",
                            Status = 0,
                            Surname = "Feeney",
                            Tckn = "47167362758"
                        },
                        new
                        {
                            ID = 3,
                            BirthDate = new DateTime(1973, 10, 20, 23, 2, 17, 878, DateTimeKind.Local).AddTicks(7902),
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 235, DateTimeKind.Local).AddTicks(2137),
                            Name = "Randi",
                            Status = 0,
                            Surname = "Dicki",
                            Tckn = "23176272794"
                        },
                        new
                        {
                            ID = 4,
                            BirthDate = new DateTime(1987, 1, 18, 1, 3, 53, 98, DateTimeKind.Local).AddTicks(359),
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 235, DateTimeKind.Local).AddTicks(2159),
                            Name = "Jillian",
                            Status = 0,
                            Surname = "Fisher",
                            Tckn = "73116014597"
                        },
                        new
                        {
                            ID = 5,
                            BirthDate = new DateTime(1974, 5, 22, 20, 19, 21, 627, DateTimeKind.Local).AddTicks(2277),
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 235, DateTimeKind.Local).AddTicks(2178),
                            Name = "Jonatan",
                            Status = 0,
                            Surname = "Blanda",
                            Tckn = "06361966448"
                        },
                        new
                        {
                            ID = 6,
                            BirthDate = new DateTime(1997, 10, 5, 11, 25, 8, 328, DateTimeKind.Local).AddTicks(5975),
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 235, DateTimeKind.Local).AddTicks(2200),
                            Name = "Guiseppe",
                            Status = 0,
                            Surname = "Lynch",
                            Tckn = "58174158764"
                        },
                        new
                        {
                            ID = 7,
                            BirthDate = new DateTime(1998, 10, 14, 0, 26, 52, 647, DateTimeKind.Local).AddTicks(7683),
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 235, DateTimeKind.Local).AddTicks(2218),
                            Name = "Trudie",
                            Status = 0,
                            Surname = "Brakus",
                            Tckn = "43306869133"
                        },
                        new
                        {
                            ID = 8,
                            BirthDate = new DateTime(1987, 4, 5, 17, 38, 23, 58, DateTimeKind.Local).AddTicks(2903),
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 235, DateTimeKind.Local).AddTicks(2235),
                            Name = "Elias",
                            Status = 0,
                            Surname = "Donnelly",
                            Tckn = "70527593908"
                        },
                        new
                        {
                            ID = 9,
                            BirthDate = new DateTime(1972, 3, 10, 13, 31, 49, 639, DateTimeKind.Local).AddTicks(8188),
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 235, DateTimeKind.Local).AddTicks(2252),
                            Name = "Moshe",
                            Status = 0,
                            Surname = "Roob",
                            Tckn = "86112110274"
                        },
                        new
                        {
                            ID = 10,
                            BirthDate = new DateTime(1975, 12, 21, 11, 19, 57, 314, DateTimeKind.Local).AddTicks(1967),
                            CreatedComputerName = "BILGIISLEM",
                            CreatedDate = new DateTime(2024, 11, 22, 14, 7, 18, 235, DateTimeKind.Local).AddTicks(2269),
                            Name = "Cristal",
                            Status = 0,
                            Surname = "Kreiger",
                            Tckn = "51589906127"
                        });
                });

            modelBuilder.Entity("MODEL.Entities.TeacherBranch", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedComputerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TeacherId", "BranchId");

                    b.HasIndex("BranchId");

                    b.ToTable("TeacherBranches");
                });

            modelBuilder.Entity("MODEL.Entities.Vehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CreatedComputerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Transmission")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("MODEL.Entities.VehicleBranch", b =>
                {
                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedComputerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedComputerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BranchId", "VehicleId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleBranches");
                });

            modelBuilder.Entity("MODEL.Entities.Schedule", b =>
                {
                    b.HasOne("MODEL.Entities.Student", "Student")
                        .WithMany("Schedules")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODEL.Entities.Teacher", "Teacher")
                        .WithMany("Schedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MODEL.Entities.Student", b =>
                {
                    b.HasOne("MODEL.Entities.Branch", "Branch")
                        .WithMany("Students")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("MODEL.Entities.TeacherBranch", b =>
                {
                    b.HasOne("MODEL.Entities.Branch", "Branch")
                        .WithMany("TeacherBranches")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODEL.Entities.Teacher", "Teacher")
                        .WithMany("TeacherBranches")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MODEL.Entities.VehicleBranch", b =>
                {
                    b.HasOne("MODEL.Entities.Branch", "Branch")
                        .WithMany("VehicleBranches")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MODEL.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleBranches")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("MODEL.Entities.Branch", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("TeacherBranches");

                    b.Navigation("VehicleBranches");
                });

            modelBuilder.Entity("MODEL.Entities.Student", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("MODEL.Entities.Teacher", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("TeacherBranches");
                });

            modelBuilder.Entity("MODEL.Entities.Vehicle", b =>
                {
                    b.Navigation("VehicleBranches");
                });
#pragma warning restore 612, 618
        }
    }
}
